import React, { useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { X, Printer, Share2, Copy, ShieldCheck, AlertTriangle, Check } from 'lucide-react';
import { Patient, Medication, Allergy } from '../types';
import { toLocalDateStr } from '../services/ruleEngine';

interface MedicationSummaryProps {
  isOpen: boolean;
  onClose: () => void;
  patient: Patient;
  medications: Medication[];
  allergies: Allergy[];
}

function ageFrom(dob: string): string {
  const birth = new Date(dob);
  if (isNaN(birth.getTime())) return '';
  const today = new Date();
  let age = today.getFullYear() - birth.getFullYear();
  const m = today.getMonth() - birth.getMonth();
  if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) age--;
  return age >= 0 ? `${age} yrs` : '';
}

function Row({ label, value }: { label: string; value?: React.ReactNode }) {
  if (value === undefined || value === null || value === '') return null;
  return (
    <div className="flex gap-2 text-[11px] leading-snug">
      <span className="text-slate-500 dark:text-zinc-400 min-w-[84px] shrink-0">{label}</span>
      <span className="text-slate-800 dark:text-zinc-200 font-medium">{value}</span>
    </div>
  );
}

export const MedicationSummary: React.FC<MedicationSummaryProps> = ({
  isOpen,
  onClose,
  patient,
  medications,
  allergies
}) => {
  const [copied, setCopied] = useState(false);

  const activeMeds = useMemo(
    () => medications.filter(m => m.patientID === patient.patientID && m.status === 'active'),
    [medications, patient.patientID]
  );

  const patientAllergies = useMemo(
    () => allergies.filter(a => a.patientID === patient.patientID),
    [allergies, patient.patientID]
  );

  const generatedOn = toLocalDateStr();
  const age = ageFrom(patient.dateOfBirth);

  const plainText = useMemo(() => {
    const lines: string[] = [];
    lines.push('MEDSAFE — MEDICATION LIST');
    lines.push(`Patient: ${patient.fullName}`);
    lines.push(
      `DOB: ${patient.dateOfBirth}${age ? ` (${age})` : ''}` +
        `${patient.gender ? ` · ${patient.gender}` : ''}` +
        `${patient.bloodGroup ? ` · Blood ${patient.bloodGroup}` : ''}`
    );
    if (patient.conditionTags?.length) lines.push(`Conditions: ${patient.conditionTags.join(', ')}`);
    lines.push('');
    lines.push('ALLERGIES:');
    if (patientAllergies.length === 0) {
      lines.push('  No known drug allergies documented');
    } else {
      patientAllergies.forEach(a =>
        lines.push(`  - ${a.allergenName} (${a.reactionSeverity})${a.symptoms ? ` — ${a.symptoms}` : ''}`)
      );
    }
    lines.push('');
    lines.push(`CURRENT MEDICATIONS (${activeMeds.length}):`);
    if (activeMeds.length === 0) {
      lines.push('  No active prescriptions recorded');
    } else {
      activeMeds.forEach((m, i) => {
        lines.push(`  ${i + 1}. ${m.drugName} ${m.dosage}`);
        lines.push(`     Dose: ${m.schedule} · ${m.quantityPerDose} x ${m.dosesPerDay}/day`);
        lines.push(`     Quantity remaining: ${m.quantityRemaining}`);
        lines.push(`     Prescribed: ${m.prescribedDate}`);
        if (m.instructions) lines.push(`     Notes: ${m.instructions}`);
      });
    }
    lines.push('');
    lines.push(`Generated by MedSafe on ${generatedOn}. Decision-support only — not a prescription.`);
    return lines.join('\n');
  }, [patient, activeMeds, patientAllergies, age, generatedOn]);

  if (!isOpen) return null;

  const handleShare = async () => {
    const nav = navigator as Navigator & { share?: (data: ShareData) => Promise<void> };
    if (nav.share) {
      try {
        await nav.share({ title: `Medication list — ${patient.fullName}`, text: plainText });
        return;
      } catch {
        /* user cancelled — fall through to copy */
        return;
      }
    }
    await copyText();
  };

  const copyText = async () => {
    try {
      await navigator.clipboard.writeText(plainText);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      window.alert(plainText);
    }
  };

  return createPortal(
    <div className="print-root fixed inset-0 z-50 overflow-y-auto bg-slate-200 dark:bg-zinc-950">
      {/* Screen-only toolbar */}
      <div className="no-print sticky top-0 z-10 bg-white dark:bg-zinc-900 border-b border-slate-200 dark:border-zinc-800 px-3 py-2 flex items-center justify-between gap-2 safe-top">
        <button
          onClick={onClose}
          className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-semibold text-slate-700 dark:text-zinc-300 hover:bg-slate-100 dark:hover:bg-zinc-800 transition"
        >
          <X className="w-4 h-4" />
          <span>Close</span>
        </button>
        <div className="flex items-center gap-1.5">
          <button
            onClick={handleShare}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-semibold text-teal-700 dark:text-teal-300 border border-teal-200 dark:border-teal-900/60 hover:bg-teal-50 dark:hover:bg-teal-950/30 transition"
          >
            <Share2 className="w-3.5 h-3.5" />
            <span>Share</span>
          </button>
          <button
            onClick={copyText}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-semibold text-slate-700 dark:text-zinc-300 border border-slate-300 dark:border-zinc-700 hover:bg-slate-100 dark:hover:bg-zinc-800 transition"
            title="Copy as plain text"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy'}</span>
          </button>
          <button
            onClick={() => window.print()}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold text-white bg-teal-700 hover:bg-teal-800 transition shadow-xs"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print</span>
          </button>
        </div>
      </div>

      {/* The sheet — everything below is what gets printed */}
      <div className="print-sheet max-w-2xl mx-auto my-4 bg-white text-slate-900 shadow-xl rounded-lg border border-slate-200 overflow-hidden">
        <div className="p-6 sm:p-8 space-y-5">
          {/* Letterhead */}
          <div className="flex items-start justify-between gap-4 border-b-2 border-teal-700 pb-3">
            <div className="flex items-center gap-2.5">
              <div className="w-9 h-9 rounded-lg bg-teal-700 text-white flex items-center justify-center">
                <ShieldCheck className="w-5 h-5" />
              </div>
              <div>
                <div className="text-base font-bold leading-tight">Medication List</div>
                <div className="text-[11px] text-slate-500">Generated by MedSafe · {generatedOn}</div>
              </div>
            </div>
            <div className="text-right text-[11px] text-slate-500 leading-tight">
              <div className="font-semibold text-slate-700">{patient.fullName}</div>
              <div>ID #{String(patient.patientID).padStart(4, '0')}</div>
            </div>
          </div>

          {/* Patient */}
          <section>
            <h2 className="text-[11px] font-bold uppercase tracking-wide text-teal-800 mb-1.5">Patient</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1">
              <Row label="Full name" value={patient.fullName} />
              <Row label="Date of birth" value={`${patient.dateOfBirth}${age ? ` (${age})` : ''}`} />
              <Row label="Sex" value={patient.gender} />
              <Row label="Blood group" value={patient.bloodGroup} />
              <Row label="Phone" value={patient.contactNumber} />
              <Row
                label="Emergency"
                value={
                  patient.emergencyContact
                    ? `${patient.emergencyContact.name} (${patient.emergencyContact.relationship}) — ${patient.emergencyContact.phone}`
                    : undefined
                }
              />
            </div>
            {patient.conditionTags?.length > 0 && (
              <div className="mt-2">
                <span className="text-[11px] text-slate-500 mr-2">Active conditions:</span>
                <span className="text-[11px] font-semibold">
                  {patient.conditionTags.join(' · ')}
                </span>
              </div>
            )}
          </section>

          {/* Allergies */}
          <section>
            <h2 className="text-[11px] font-bold uppercase tracking-wide text-teal-800 mb-1.5">Drug allergies</h2>
            {patientAllergies.length === 0 ? (
              <p className="text-[11px] text-slate-600">No known drug allergies documented.</p>
            ) : (
              <div className="space-y-1">
                {patientAllergies.map(a => (
                  <div key={a.allergyID} className="flex flex-wrap items-center gap-1.5 text-[11px]">
                    <span className="font-semibold">{a.allergenName}</span>
                    <span
                      className={`px-1.5 py-0.5 rounded text-[10px] font-bold uppercase ${
                        a.reactionSeverity === 'severe'
                          ? 'bg-rose-100 text-rose-800'
                          : 'bg-amber-100 text-amber-800'
                      }`}
                    >
                      {a.reactionSeverity}
                    </span>
                    {a.symptoms && <span className="text-slate-500">— {a.symptoms}</span>}
                    <span className="text-slate-400">({a.documentedDate})</span>
                  </div>
                ))}
              </div>
            )}
          </section>

          {/* Medications */}
          <section>
            <h2 className="text-[11px] font-bold uppercase tracking-wide text-teal-800 mb-1.5">
              Current medications ({activeMeds.length})
            </h2>
            {activeMeds.length === 0 ? (
              <p className="text-[11px] text-slate-600">No active prescriptions recorded.</p>
            ) : (
              <div className="space-y-2">
                {activeMeds.map((m, i) => (
                  <div key={m.medicationID} className="border border-slate-200 rounded p-2.5">
                    <div className="flex flex-wrap items-baseline justify-between gap-2">
                      <div className="text-sm font-bold">
                        <span className="text-slate-400 font-mono text-xs mr-1.5">{i + 1}.</span>
                        {m.drugName} <span className="font-semibold">{m.dosage}</span>
                      </div>
                      <div className="text-[11px] font-mono text-slate-500">
                        {m.quantityRemaining} units left
                      </div>
                    </div>
                    <div className="mt-1.5 grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1">
                      <Row label="Schedule" value={m.schedule} />
                      <Row label="Dose" value={`${m.quantityPerDose} per dose, ${m.dosesPerDay}× daily`} />
                      <Row label="Prescribed" value={m.prescribedDate} />
                      <Row label="For" value={m.conditionCategory} />
                      {m.instructions && (
                        <div className="sm:col-span-2">
                          <Row label="Directions" value={m.instructions} />
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>

          {/* Notes / disclaimer */}
          {patient.clinicalNotes && (
            <section>
              <h2 className="text-[11px] font-bold uppercase tracking-wide text-teal-800 mb-1.5">Clinical notes</h2>
              <p className="text-[11px] text-slate-700 leading-relaxed italic border-l-2 border-slate-300 pl-2.5">
                {patient.clinicalNotes}
              </p>
            </section>
          )}

          <div className="flex items-start gap-2 border-t border-slate-200 pt-3 text-[10px] text-slate-500 leading-relaxed">
            <AlertTriangle className="w-3.5 h-3.5 text-amber-500 shrink-0 mt-0.5" />
            <p>
              Compiled from self-recorded data on the patient's device. MedSafe is a decision-support
              aid and does not prescribe or diagnose — verify against the official chart before
              clinical use. Screened against WHO ATC / BNF / FDA guidance where applicable.
            </p>
          </div>
        </div>
      </div>
    </div>,
    document.body
  );
};
